#!/bin/sh

case "$(file -Lb --mime-type -- "$1")" in
	image/*)
		# chafa -f sixel -s "$2x$3" --animate off --polite on "$1"
		viu --absolute-offset  --frame-rate 10 --transparent --height 10 "$1"
		exiftool "$1"
		exit $?
		;;
	*)
		~/.config/lf/pv.sh "$1"
		;;
esac
