# ln -sf "$DOT_FILE/etc/cargo_binstall.toml" "$CARGO_HOME/binstall.toml"
# https://github.com/cargo-bins/cargo-binstall


confirm = true
track_installs = true
continue_on_failure = false
strategies = []

[telemetry]
enabled = false
consent_asked = true
