theme = "ayu_evolve"

[editor]
	# lsp.enable = false # This turns off all LSP features for all languages
	scrolloff = 15
	# color = true
	auto-format = false
	line-number = "relative"
	bufferline = "multiple"

	[editor.cursor-shape]
		insert = "bar"
		select = "underline"

	[editor.indent-guides]
		# render = true
		character = "┆" # Some characters that work well: "▏", "┆", "┊", "⸽"
		skip-levels = 1

	[editor.whitespace]
		[editor.whitespace.render]
			space = "none"
			tab = "all"
			nbsp = "none"
			nnbsp = "none"
			newline = "all"

		[editor.whitespace.characters]
			space = "·"
			tab = "-"
			newline = "¬"
			# tabpad = "·"  # Tabs will look like "→···" (depending on tab width)

	[editor.lsp]
		display-inlay-hints = true
		enable = false

	[editor.auto-save]
		focus-lost = true

	[editor.statusline]
		left = ["mode", "spinner"]
		center = ["file-name"]
		right = [
			"diagnostics",
			"selections",
			"position",
			"file-encoding",
			"file-line-ending",
			"file-type",
		]
		separator = "│"
		mode.normal = "NORMAL"
		mode.insert = "INSERT"
		mode.select = "SELECT"
		diagnostics = ["warning", "error"]
		workspace-diagnostics = ["warning", "error"]

[keys.normal]
	G = "goto_last_line"
	[keys.normal."z"]
		o = ":run-shell-command zed --existing %{buffer_name}"
		r = ":lsp-restart"
		R = ":config-reload"
		t = ":toggle lsp.enable"
