# https://github.com/pimalaya/himalaya/blob/master/config.sample.toml

display-name = "pritam@Dhanno"
downloads-dir = "~/Downloads/himhimalaya"
# table.preset = "││──╞═╪╡┆    ┬┴┌┐└┘"

[accounts.GmailPritam12426]
	default = true
	email = "<example@gmail.com>"
	display-name = "<Gmail (pritam@Dhanno)>"

	signature-delim = "\n-- \n"
	signature = "~/.config/himalaya/gmail/signature.txt"

	downloads-dir = "~/Downloads/himhimalaya/gmail/<pritam-Dhanno>"

	folder.aliases.inbox = "INBOX"
	folder.aliases.sent = "[Gmail]/Sent Mail"
	folder.aliases.drafts = "[Gmail]/Drafts"
	folder.aliases.trash = "[Gmail]/Bin"

	envelope.list.page-size = 30 # the number of message to show by page.
	envelope.list.datetime-fmt = "%a %b-%d-%Y %I:%M %p"
	envelope.list.table.unseen-char = "🙈"

	imap.sasl.plain.authcid = "pritamkumar12426@gmail.com"
	imap.sasl.plain.passwd.command = "cat /Users/pritam/.cache/google_auth_key_temp.txt"  # https://myaccount.google.com/security
	imap.server = "imaps://imap.gmail.com:993"
	mailbox.alias.inbox = "INBOX"
	smtp.sasl.plain.authcid = "pritamkumar12426@gmail.com"
	smtp.sasl.plain.passwd.command = "cat /Users/pritam/.cache/google_auth_key_temp.txt"
	smtp.server = "smtps://smtp.gmail.com:465"
