# https://github.com/pimalaya/himalaya/blob/master/config.sample.toml
display-name = "pritam@Dhanno"
downloads-dir = "~/Downloads/himhimalaya"

[accounts.GmailPritam12426]
	default = true
	email = "<example@gmail.com>"
	display-name = "<Gmail (pritam@Dhanno)>"

	signature-delim = "\n-- \n"
	signature = "~/.config/himalaya/gmail/signature.txt"

	downloads-dir = "~/Downloads/himhimalaya/gmail/<pritam-Dhanno>"

	folder.aliases.inbox = "INBOX"
	folder.aliases.sent = "[Gmail]/Sent Mail"
	folder.aliases.drafts = "[Gmail]/Drafts"
	folder.aliases.trash = "[Gmail]/Bin"

	envelope.list.page-size = 30 # the number of message to show by page.
	envelope.list.datetime-fmt = "%a %b-%d-%Y %I:%M %p"
	envelope.list.table.preset = "││──╞═╪╡┆    ┬┴┌┐└┘"
	envelope.list.table.unseen-char = "🙈"

	backend.type = "imap"
	backend.host = "imap.gmail.com"
	backend.port = 993
	backend.login = "example@gmail.com"
	backend.encryption.type = "tls"
	backend.auth.type = "password"
	backend.auth.raw = "<get this pass form>" # https://myaccount.google.com/security
	message.send.backend.type = "smtp"
	message.send.backend.host = "smtp.gmail.com"
	message.send.backend.port = 465
	message.send.backend.login = "<example@gmail.com>"
	message.send.backend.encryption.type = "tls"
	message.send.backend.auth.type = "password"
	message.send.backend.auth.raw = "<get this pass form>" # https://myaccount.google.com/security
